spring.application.name=brazilian_commerce

# Server settings
server.address=::
server.port=8080
# DB credentials and settings
# reWriteBatchedInserts=true merges insert statements
spring.datasource.url=jdbc:postgresql://localhost:5432/commerce?reWriteBatchedInserts=true
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# SQL logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Hibernate writing to DB settings
spring.jpa.properties.hibernate.jdbc.batch_size=10000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
# Batch size used in data load transaction
dataload.batch_size=10000

# Thymeleaf settings
spring.thymeleaf.cache=false
